services:
# ----- Auto groups notification types -----
# Scope MUST be prototype for all the plugins to work.
    phpbb.autogroups.notification.type.group_added:
        class: phpbb\autogroups\notification\type\group_added
        scope: prototype
        parent: notification.type.base
        tags:
            - { name: notification.type }

    phpbb.autogroups.notification.type.group_removed:
        class: phpbb\autogroups\notification\type\group_removed
        scope: prototype
        parent: notification.type.base
        tags:
            - { name: notification.type }
