imports:
    - { resource: conditions.yml }
    - { resource: cron.yml }
    - { resource: notifications.yml }
    - { resource: tables.yml }

services:
    phpbb.autogroups.listener:
        class: phpbb\autogroups\event\listener
        arguments:
            - @phpbb.autogroups.manager
        tags:
            - { name: event.listener }

    phpbb.autogroups.admin_controller:
        class: phpbb\autogroups\controller\admin_controller
        arguments:
            - @dbal.conn
            - @log
            - @phpbb.autogroups.manager
            - @request
            - @template
            - @user
            - %phpbb.autogroups.tables.autogroups_rules%
            - %phpbb.autogroups.tables.autogroups_types%
